<a href="https://colab.research.google.com/github/mahaairshad/CE888_si19783/blob/master/Lab1/Lab1_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Lab TaskQuestions

####1. Create a (4 x 2) integer array and print it's attributes

In [0]:
import numpy as np
a = np.array([[ 6, 9, 2, 3],
              [3,5,4,10]])
print(a)

[[ 6  9  2  3]
 [ 3  5  4 10]]


####2. Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
b=np.random.randint(1,10, 10)
print(b)

[4 9 5 1 6 1 5 5 2 3]


In [0]:
#ascending
print(np.sort(b))

[1 1 2 3 4 5 5 5 6 9]


In [0]:
#descending
print(-np.sort(-b))

[9 6 5 5 5 4 3 2 1 1]


####3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [0]:
c=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(c)

[1 2 3 4 5 6 7 8 9]


In [0]:
d=c[0:3]
print(d)
e=c[3:6]
print(e)
f=c[6:9]
print(f)
k=np.array([d,e,f])
print (k)

[1 2 3]
[4 5 6]
[7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


####4. Stack two arrays of any size horizontally and vertically

In [0]:
#vertical
print(np.stack((f,d), axis=-1))
#horizontal
print(np.stack((f,d)))

[[7 1]
 [8 2]
 [9 3]]
[[7 8 9]
 [1 2 3]]


####5. Create two array of same size and find commom elements

In [0]:
x=np.array([30, 22, 10, 13, 4])
y=np.array([22, 2, 55, 10, 44])
print(np.intersect1d(x, y))

[10 22]


####6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

####7. Create an array of size 100 and compute the mean, median, standard deviation.

####8. Normalize a 5x5 random matrix

####9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?