<a href="https://colab.research.google.com/github/mahaairshad/CE888_si19783/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Lab TaskQuestions

####1. Create a (4 x 2) integer array and print it's attributes

In [1]:
import numpy as np
a = np.array([[ 6, 9, 2, 3],
              [3,5,4,10]])
print(a)

[[ 6  9  2  3]
 [ 3  5  4 10]]


####2. Create an array of dimension (1,10) and sort it in ascending and descending order

In [2]:
b=np.random.randint(1,10, 10)
print(b)

[3 7 3 2 2 3 6 9 9 9]


In [3]:
#ascending
print(np.sort(b))

[2 2 3 3 3 6 7 9 9 9]


In [4]:
#descending
print(-np.sort(-b))

[9 9 9 7 6 3 3 3 2 2]


####3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [5]:
c=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(c)

[1 2 3 4 5 6 7 8 9]


In [6]:
d=c[0:3]
print(d)
e=c[3:6]
print(e)
f=c[6:9]
print(f)
k=np.array([d,e,f])
print (k)

[1 2 3]
[4 5 6]
[7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


####4. Stack two arrays of any size horizontally and vertically

In [7]:
#vertical
print(np.stack((f,d), axis=-1))
#horizontal
print(np.stack((f,d)))

[[7 1]
 [8 2]
 [9 3]]
[[7 8 9]
 [1 2 3]]


####5. Create two array of same size and find commom elements

In [8]:
x=np.array([30, 22, 10, 13, 4])
y=np.array([22, 2, 55, 10, 44])
print(np.intersect1d(x, y))

[10 22]


####6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [9]:
g=np.random.randint(1,20,size=(5,5))
print(g)

[[ 9  2  9  2 19]
 [19 18  8  6 15]
 [14  2 16  2 10]
 [15 19  4  4  6]
 [16 16 19  7 15]]


In [10]:
#Minimum across columns
np.min(g,axis=0)

array([9, 2, 4, 2, 6])

In [11]:
#Minimum across rows
np.min(g,axis=1)

array([2, 6, 2, 4, 7])

In [12]:
#Maximum across columns
np.max(g,axis=0)

array([19, 19, 19,  7, 19])

In [13]:
#Maximum across rows
np.max(g,axis=1)

array([19, 19, 16, 19, 19])

####7. Create an array of size 100 and compute the mean, median, standard deviation.

In [14]:
r=np.random.randint(1,30,size=(1,100))
print(r)

[[29  7 26 25 16 29  5 26 17 11 23 16 29  9 25 28  3 23 15 27  7 22 17 23
  16  4 28 28 29  7 21 27  2 11  3 21 24 28  9  7 14 17 10  9 26 11 14 21
  18 14 22 29 26  3 17 17 15 14  9 27 19  6 10 13 24  6 21  4  8  8  8 25
  16 12  4 26 27 19  7  6 27  4 25 20  8 26 21  5 28  4 13 16 23 19  9 13
  21  4  1  8]]


In [15]:
np.mean(r)

16.2

In [16]:
np.median(r)

16.0

In [17]:
np.std(r)

8.48528137423857

####8. Normalize a 5x5 random matrix

In [18]:
n=np.random.randint(5,11,size=(5,5))
print(n)

[[ 5  8  9  5  8]
 [ 8  8  9  8  5]
 [10  8  9  9  6]
 [ 6  6  8  7  6]
 [ 6  9  5 10  8]]


In [19]:
n=n-np.mean(n)
n=n/(np.std(n))
print(n)

[[-1.54740618  0.3551424   0.98932526 -1.54740618  0.3551424 ]
 [ 0.3551424   0.3551424   0.98932526  0.3551424  -1.54740618]
 [ 1.62350813  0.3551424   0.98932526  0.98932526 -0.91322332]
 [-0.91322332 -0.91322332  0.3551424  -0.27904046 -0.91322332]
 [-0.91322332  0.98932526 -1.54740618  1.62350813  0.3551424 ]]


####9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [24]:
a=np.random.randint(1,20,size=(4,4,3))
print(a)

[[[18  1 16]
  [ 3 16  9]
  [ 3  9  6]
  [ 2  4  2]]

 [[ 3 16  9]
  [ 7  1 19]
  [ 5  3  6]
  [15 18 13]]

 [[19  7 17]
  [10 19 16]
  [16 14 13]
  [ 2 17  7]]

 [[ 1 12  8]
  [17  2 11]
  [15  6 18]
  [19  2 13]]]


In [30]:
b=np.random.randint(1,20,size=(3,4))
print(b)

[[ 8 13  9 10]
 [ 6  1 16  2]
 [12  2  3 12]]


In [28]:
c=b.reshape((8,2))
print(c)

[[16  9]
 [16 12]
 [14  3]
 [18 13]
 [15 13]
 [13  3]
 [17 16]
 [18 19]]


In [31]:
np.matmul(a,b)

array([[[342, 267, 226, 374],
        [228,  73, 310, 170],
        [150,  60, 189, 120],
        [ 64,  34,  88,  52]],

       [[228,  73, 310, 170],
        [290, 130, 136, 300],
        [130,  80, 111, 128],
        [384, 239, 462, 342]],

       [[398, 288, 334, 408],
        [386, 181, 442, 330],
        [368, 248, 407, 344],
        [202,  57, 311, 138]],

       [[176,  41, 225, 130],
        [280, 245, 218, 306],
        [372, 237, 285, 378],
        [320, 275, 242, 350]]])